// Auto-generated by scripts/register-commands.js — do not edit by hand.
// Regenerate with `npm run register-commands` any time a command is
// added, renamed, or removed.
export const COMMAND_IDS = {
  "Quick access": "1544131011775041688",
  "help": "1537593484817735720",
  "about": "1541086379675492495",
  "forget-me": "1537799029495304253",
  "privacy-policy": "1538197819293434000",
  "feedback": "1538369091641933936",
  "free": "1535972417682407504",
  "trending": "1541638031709311057",
  "bundles": "1549381703624298516",
  "price": "1528834781020946462",
  "wishlist": "1530999210944499912",
  "config": "1532146657108426772"
} as const
