// Auto-generated by scripts/register-commands.js — do not edit by hand.
// Scope: global commands (IDs differ between guild and global scope).
// Regenerate with `npm run register-commands:global` (or
// `npm run register-commands` for guild-scoped testing) any time a
// command is added, renamed, or removed.
export const COMMAND_IDS = {
  "Quick access": "1556228675035201566",
  "help": "1556228675035201567",
  "about": "1556228675035201568",
  "forget-me": "1556228675035201569",
  "privacy-policy": "1556228675035201570",
  "feedback": "1556228675035201571",
  "free": "1556228675035201572",
  "trending": "1556228675035201573",
  "bundles": "1556228675035201574",
  "price": "1556228675035201575",
  "wishlist": "1556228675178070056",
  "config": "1556228675178070057"
} as const
